export { setupElementPlus } from './element-plus'
export { setupElementPlusIcons } from './element-plus-icons'
export { setupAppIcon } from './app-icon'
export { setupRouterGuard } from './router-guard'
export { setupRSW } from './register-service-worker'
